server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php;

    # Permitimos peticiones de hasta 6 MB para que Nginx
    # no bloquee las imágenes antes de que lleguen a PHP.
    # ImageService aplica después el límite real de 5 MB
    # al archivo recibido.
    client_max_body_size 6M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_pass app:9000;
    }

    location ~ /\. {
        deny all;
    }
}